import {
  LABOR_DATA_TRACKING_SYSTEM,
  LOCATION_TYPES,
  OVERTIME_TRACKING_TYPE,
  POS_IMPORT_TYPES,
  SOS_SYSTEM,
} from "./enums";

export interface LocationRequest {
  userId: string;
  location: Location;
}

export type LocationType = (typeof LOCATION_TYPES)[keyof typeof LOCATION_TYPES];
export type SOSSystemName = keyof typeof SOS_SYSTEM;
export type POSImportType = (typeof POS_IMPORT_TYPES)[keyof typeof POS_IMPORT_TYPES];
export type LaborDataTrackingSystem =
  (typeof LABOR_DATA_TRACKING_SYSTEM)[keyof typeof LABOR_DATA_TRACKING_SYSTEM];
export type OvertimeTrackingType =
  (typeof OVERTIME_TRACKING_TYPE)[keyof typeof OVERTIME_TRACKING_TYPE];

export interface Address {
  Address1: string;
  Address2: string | null;
  AddressType: "Shipping";
  City: string;
  Country: string;
  CountryName: string;
  IsVerified: boolean;
  Latitude: number;
  Longitude: number;
  PostalCode: string;
  State: string;
}

export interface Location {
  AdditionalInfoLabelList: {
    AdditionalInfoNumber1Label: string;
    AdditionalInfoNumber2Label: string;
    AdditionalInfoNumber3Label: string;
    AdditionalInfoText1Label: string;
    AdditionalInfoText2Label: string;
  };
  AdditionalInfoNumber1: number | null;
  AdditionalInfoNumber2: number | null;
  AdditionalInfoNumber3: number | null;
  AdditionalInfoText1: string | null;
  AdditionalInfoText2: string | null;
  AddressValidated: boolean;
  CateringItemTypeTemplate: string | null;
  ClientId: string | null;
  CommissaryLocation: string | null;
  ComparableStartDate: string | null;
  ConcatenationEnabled: boolean;
  CreatedBy: string | null;
  CreatedOn: string | null;
  CurrentComidaVersion: string | null;
  DTS: string | null;
  EnableEmployeePush: boolean;
  EnableR365Messaging: boolean;
  EnableSmartLabor: boolean;
  EstablishmentNumber: string | null;
  ExcludeFromSchedule: boolean;
  FileID: string | null;
  FoodType: string | null;
  ForecastLaborDriveType: number | null;
  ForecastLaborMinimumType: number | null;
  FormId: string | null;
  FormName: string | null;
  HasLogo: boolean;
  Id: string;
  ImportDDP: boolean;
  ImportRevenueCenters: number | null;
  ImportTill: number | null;
  IsActive: boolean;
  IsBillingDifferent: boolean;
  IsComparableStartDateSetAutomatically: boolean;
  IsConfiguredForR365Payments: boolean;
  IsIntraDay: number;
  IsNonComparableLocation: boolean;
  IsSpeedOfService: number;
  IsStandaloneScheduling: boolean;
  LabelList: {
    Category1: string;
    Category2: string | null;
    Category3: string | null;
    Category4: string | null;
    Category5: string | null;
    Category6: string | null;
    Category7: string | null;
    Category8: string | null;
    Category9: string | null;
    Category10: string | null;
  };
  LaborDataTrackingSystem: LaborDataTrackingSystem;
  LocationAddresses: Address[];
  LocationCategory1: string | null;
  LocationCategory1Name: string | null;
  LocationCategory2: string | null;
  LocationCategory2Name: string | null;
  LocationCategory3: string | null;
  LocationCategory3Name: string | null;
  LocationCategory4: string | null;
  LocationCategory4Name: string | null;
  LocationCategory5: string | null;
  LocationCategory5Name: string | null;
  LocationCategory6: string | null;
  LocationCategory6Name: string | null;
  LocationCategory7: string | null;
  LocationCategory7Name: string | null;
  LocationCategory8: string | null;
  LocationCategory8Name: string | null;
  LocationCategory9: string | null;
  LocationCategory9Name: string | null;
  LocationCategory10: string | null;
  LocationCategory10Name: string | null;
  LogCategories: string[];
  ModifiedBy: string | null;
  ModifiedOn: string | null;
  ModuleInactiveStatus: number;
  MostRecentDSSDate: string | null;
  NameOnCheck: string | null;
  OnlineOrderEmployee: string | null;
  OpenDate: string | null;
  POSCurrency: string | null;
  POSGroup: string | null;
  POSImportTime: string | null;
  PayTaxesOnCreditCardTips: boolean;
  PaymentTypeRevenueCenter: number;
  PayrollLocationID: string | null;
  PermanentCloseDate: string | null;
  R365LocationType: LocationType;
  SOSStartDate: string | null;
  SOSStartDateString: string | null;
  SOSSystem: SOSSystemName;
  SPLH: number;
  SPLHFriday: number;
  SPLHMonday: number;
  SPLHSaturday: number;
  SPLHSunday: number;
  SPLHThursday: number;
  SPLHTuesday: number;
  SPLHWednesday: number;
  SalesTaxRate: number | null;
  StartDate: string | null;
  SyscoLocationNumber: string | null;
  TaskLists: string[];
  TimeZoneId: string;
  TipEditEnabled: boolean;
  UseLaborInCode: boolean;
  UseTills: boolean;
  WritebackType: number;
  activeIntraDayLocationCount: number;
  activeSpeedOfServiceLocationCount: number;
  depositAccountId: string | null;
  depositAccountName: string | null;
  dm_APAccount: string | null;
  dm_AWS: string | null;
  dm_Attribute1: string | null;
  dm_Attribute2: string | null;
  dm_AutoImport: "true" | "false";
  dm_BreakPenaltiesPerDay: number | null;
  dm_CateringName: string | null;
  dm_City: string | null;
  dm_CloseTime: string | null;
  dm_ClosingEmployee: string | null;
  dm_ClosingTime: string | null;
  dm_CompEndDate: string | null;
  dm_CompEndDateString: string | null;
  dm_CompStartDate: string | null;
  dm_Concept: string | null;
  dm_DailyManagerSalary: number;
  dm_DailyTargetAvgCheck: number | null;
  dm_DayPart1AvgCheckGoal: number | null;
  dm_DayPart1Name: string | null;
  dm_DayPart1StartTime: string | null;
  dm_DayPart2AvgCheckGoal: number | null;
  dm_DayPart2Name: string | null;
  dm_DayPart2StartTime: string | null;
  dm_DayPart3AvgCheckGoal: number | null;
  dm_DayPart3Name: string | null;
  dm_DayPart3StartTime: string | null;
  dm_DayPart4AvgCheckGoal: number | null;
  dm_DayPart4Name: string | null;
  dm_DayPart4StartTime: string | null;
  dm_DayPart5AvgCheckGoal: number | null;
  dm_DayPart5Name: string | null;
  dm_DayPart5StartTime: string | null;
  dm_DayPart6AvgCheckGoal: number | null;
  dm_DayPart6Name: string | null;
  dm_DayPart6StartTime: string | null;
  dm_DayPartStartTime1: string | null;
  dm_DayPartStartTime2: string | null;
  dm_DayPartStartTime3: string | null;
  dm_DayPartStartTime4: string | null;
  dm_DayPartStartTime5: string | null;
  dm_DayPartStartTime6: string | null;
  dm_DefaultBudget: number | null;
  dm_DefaultCateringChef: string | null;
  dm_DepositOnFriday: number | null;
  dm_DepositOnMonday: number | null;
  dm_DepositOnSaturday: number | null;
  dm_DepositOnSunday: number | null;
  dm_DepositOnThursday: number | null;
  dm_DepositOnTuesday: number | null;
  dm_DepositOnWednesday: number | null;
  dm_ExcludeFromDashboard: "true" | "false";
  dm_Fax: string | null;
  dm_FinancialStatusBasedOn: "true" | "false";
  dm_ImportDaysBack: number | null;
  dm_LaborGoal: number | null;
  dm_LaborGoalFriday: number | null;
  dm_LaborGoalMonday: number | null;
  dm_LaborGoalSaturday: number | null;
  dm_LaborGoalSunday: number | null;
  dm_LaborGoalThursday: number | null;
  dm_LaborGoalTuesday: number | null;
  dm_LaborGoalWednesday: number | null;
  dm_LegalEntity: string;
  dm_LocationManager: string | null;
  dm_LocationNumber: string;
  dm_MostRecentCloseDate: string | null;
  dm_NetSalesGoalFriday: number | null;
  dm_NetSalesGoalMonday: number | null;
  dm_NetSalesGoalSaturday: number | null;
  dm_NetSalesGoalSunday: number | null;
  dm_NetSalesGoalThursday: number | null;
  dm_NetSalesGoalTuesday: number | null;
  dm_NetSalesGoalWednesday: number | null;
  dm_OvertimeTracking: OvertimeTrackingType;
  dm_POSImportStart: string | null;
  dm_POSImportStartString: string | null;
  dm_POSImportType: POSImportType;
  dm_POSSystem: string | null;
  dm_PayTipsWithPayroll: "true" | "false";
  dm_PayrollBenefitEstimate: number;
  dm_PayrollOtherEstimate: number;
  dm_PayrollTaxEstimate: number;
  dm_PettyCashInDailyClose: "true" | "false";
  dm_Phone1: string | null;
  dm_Phone2: string | null;
  dm_PreviousDayLabor: number | null;
  dm_PreviousDayLaborTotal: number | null;
  dm_PreviousDaySales: number | null;
  dm_PreviousDaySalesofLastYear: number | null;
  dm_SQFT: number | null;
  dm_SalesIncreaseGoal: number | null;
  dm_SalesPercentofLastYear: number | null;
  dm_SalesTaxRate: number;
  dm_SameDayLastYearSales: number | null;
  dm_StartDate: string | null;
  dm_State: string | null;
  dm_Street1: string | null;
  dm_Street2: string | null;
  dm_WeeklyJournalEntry: string | null;
  dm_Zip: string | null;
  dm_dailymanagersalary_Base: number | null;
  dm_importtime: number | null;
  dm_mtc_financialstatus: number | null;
  dm_name: string | null;
  dm_previousdaylabortotal_Base: number | null;
  dm_previousdaysales_Base: number | null;
  dm_samedaylastyearsales_Base: number | null;
  dm_zip: { [key: string]: any };
  fileName: string | null;
  filePublicLink: string | null;
  importTimeString: string | null;
  initialPOSSystem: string | null;
//   legalEntity?: string | null;
  legalEntityReadOnly: boolean;
  locationId: string;
  locationNumber: string | null;
  masterTax: {
    reportingUnitNumber: string | null;
    worksiteIDNumber: string | null;
    worksiteDescription: string | null;
  };
  newFileName: string | null;
  overShortAccountId: string | null;
  overShortAccountName: string | null;
  pettyCashAccountId: string | null;
  pettyCashAccountName: string | null;
  startDate1String: string | null;
  startDate2String: string | null;
  startDate3String: string | null;
  startDate4String: string | null;
  startDate5String: string | null;
  startDate6String: string | null;
  thumbnailLink: string | null;
  tipsPayrollAccountId: string | null;
  tipsPayrollAccountName: string | null;
}
